volumes:
  spectacles-postgres-data:

services:
  postgres:
    image: postgres:latest
    env_file: .env.dev
    volumes:
      - spectacles-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432

  web:
    depends_on:
      - postgres
    build: .
    env_file: .env.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
