name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_docker_hub_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create env
        run: touch env.ts && echo "${{ secrets.ENV }}" > env.ts

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE }}:${{ github.sha }}

  deploy_to_ec2:
    needs: build_docker_hub_image
    runs-on:
      group: EC2
      labels: [self-hosted, linux, deploy]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove existing service
        run: |
          docker service rm ${{ secrets.IMAGE }} || true

      - name: Pull latest Docker image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE }}:latest

      - name: Deploy new service
        run: |
          docker service create \
            --name ${{ secrets.IMAGE }} \
            --replicas 1 \
            --network prod-network
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.IMAGE }}:latest \
